### ISSUE TITLE
Previous ID button, in navigator menu

### ISSUE THREAD

**Issue by gk-skymatrix** [gKript/NS-PLM#19]
Add a button to decrease the value of the code under the navigator menu. It would be very convenient if they were not nested, but directly accessible (next id too).

**Comment by asyntote** [comment]
@gk-skymatrix There is something like you described already implemented. You can fiind them under the Navigator menu when you are in a CODE context page. Please, let me know if they are what you wish. Thanks.

**Comment by asyntote** [comment]
There's already something similar.
